### PR TITLE
Fix misclassification error

### PR DESCRIPTION
**Pull request by duchoang**
- [x] Use this layer `[1200 250 100 3]` for exercise model
- [x] Don't scale the feature
- [x] Ready for review

### CODE REVIEW

**Comment by tmbo** [comment]
Is there an issue for this one? What does it fix?

**Comment by duchoang** [comment]
If we use that function `scale_features`, the range of input X, Y, Z will be dropped too low in this range: `-0.003 -> 0.0003` 

Example running the training with this dataset:

```./run_training.sh ../muvr-training-data/labelled/18-09-15-triceps-biceps-lateral/  output/```

visualisation

We get the very high error rate: `49.1%`, if I comment out that line, the error is just `0.2%`

screen shot 2015-11-10 at 12 16 48

screen shot 2015-11-10 at 12 17 51

**Comment by tmbo** [comment]
That makes sense. Is all the data scaled?

**Comment by duchoang** [comment]
I think they are already scaled. All accelerometer data are roughly in the range: `-1.5 -> 1.5`

**Comment by tmbo** [comment]
Alright. The triceps-biceps-lateral data is not scaled. So we should decide on wether to store the scaled values or not and adjust all cvs files accordingly. Do you know if the exported data we generate right now is scaled?

**Comment by duchoang** [comment]
Yes, currently all exported data from the phone is scaled, so I think we can comment that line now

screen shot 2015-11-10 at 13 52 09

screen shot 2015-11-10 at 13 53 18

**Comment by tmbo** [comment]
I guess we don't need that fix anymore, since in PR #28 the value range gets adjusted to 4 instead of 8000.

**Pull request closed without merging**
