### PR TITLE
Feature/mlp

### PR DESCRIPTION
**Pull request by janm399**
Introduces proper training of the neon models using the data from the journal.

---

This is in preparation for merge, which I have planned for 08/09 2100 BST.

### CODE REVIEW

**Comment by janm399** [comment]
@muvr/core are we OK to merge?

**Comment by tmbo** [comment]
I have added the changes I still had. The mechanism we got right now is not pretty and does include some manual steps but it is working. I will do some work tomorrow to clean things up and automate them (e.g. remove directory references and move code from R scripts to python).

**Comment by janm399** [comment]
That'd be great. We'll review the plans tomorrow morning.

**Comment by tmbo** [comment]
I nearly finished here. The scala code needs to be cleaned up a little further but besides that everything is working.

- Scala spark job is dumping the exercise examples as datasets in CSV format
- Python spark job reads datasets and learns a model for each dataset
- IPython code uses model generation of python code (reduces code in notebook)

**Comment by tmbo** [comment]
And I need to double check in the app that the model serialisation still produces the correct results.

**Comment by janm399** [comment]
Is this ready to merge?

**Pull request merged**
