### PR TITLE
Feature/spark cassandra

### PR DESCRIPTION
**Pull request by tmbo**
- [x] Run spark training for all the data in cassandra
- [x] Write model results to cassandra
- [x] Fix notebooks

----

- [x] ready for review

### CODE REVIEW

**Comment by tmbo** [comment]
The table where the models should be stored needs to be created using the following columns:
```sql
CREATE TABLE muvr.models (
    id uuid,
    labels list<text>,
    layers list<int>,
    model blob,
    model_id text,
    user_id text,
    PRIMARY KEY (id)
)
```

**Comment by zapletal-martin** [comment]
Looks good +1

**Comment by anirvanc** [comment]
@tmbo `muvr.models` table needs to be in the same `keyspace` ie. `training`?

**Comment by tmbo** [comment]
I already created it on the ring. So that should be fine.

**Comment by anirvanc** [comment]
@tmbo That's great!

I will get that included in the keyspace and table creation script.

**Comment by anirvanc** [comment]
@EslamElHusseiny can you get the `muvr.models` table creation in our cassandra automation?

**Comment by tmbo** [comment]
@anirvanc wait a minute, model should be a string. I corrected that.

**Comment by EslamElHusseiny** [comment]
@anirvanc @tmbo  Done!
I've used models table definition above

**Pull request merged**
